CREATE TABLE IF NOT EXISTS "Payslip" (
    "Month" TEXT NOT NULL,
    "Year" INTEGER NOT NULL,
    "EmpCode" TEXT PRIMARY KEY,
    "EmployeeName" TEXT NOT NULL,
    "PAN" TEXT NOT NULL,
    "BankAccount" TEXT NOT NULL,
    "Designation" TEXT NOT NULL,
    "CTC" REAL NOT NULL,
    "EarnBasic" REAL NOT NULL,
    "HRA" REAL NOT NULL,
    "MedicalAllowance" REAL NOT NULL,
    "OtherBasic" REAL NOT NULL,
    "PF" REAL NOT NULL,
    "ProfessionalTax" REAL NOT NULL,
    "ESIC" REAL NOT NULL,
    "TDS" REAL NOT NULL,
    "TotalDeductions" REAL NOT NULL,
    "Difference" REAL NOT NULL,
    "Reimburshment" REAL NOT NULL,
    "AdvancePayment" REAL NOT NULL,
    "NetPayable" REAL NOT NULL,
    "YearlyCTC" REAL NOT NULL
);
